language: cpp

compiler:
  - gcc

install:
  - pip install --user conan
  - conan

script:
  - mkdir build && cd build

  - conan install .. -s build_type=Debug
  - CC=gcc CXX=g++ cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . --target conan_test

  - ./bin/conan_test.exe
