language: cpp

compiler:
  - gcc

install:
  - pip install conan

script:
  - mkdir build && cd build

  - conan install .. 
  - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . --target conan_test

  - ./bin/conan_test.exe
