language: cpp

compiler:
  - gcc

install:
  - pip install --user conan
  - conan
  - cmake --version
  - conan --version

script:
  - mkdir build && cd build

  - conan install ..
  - cmake ..
  - cmake --build .

  - ./bin/conan_test.exe
