language: cpp

compiler:
  - gcc

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.9
  - sudo update-alternatives \
        --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 \
        --slave /usr/bin/g++ g++ /usr/bin/g++-4.9

  - pip install conan

script:
  - mkdir build && cd build

  - conan install .. \
        -s compiler=gcc \
        -s compiler.libcxx=libstdc++11 \
        -s compiler.version=4.9 \
        -s build_type=Debug
 
  - CC=gcc-4.9 CXX=g++-4.9 cmake .. \
        -G "Unix Makefiles" \
        -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . --target conan_test

  - ./bin/conan_test.exe
